name: Crear EXE ViNX0
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generar-exe:
    runs-on: windows-latest
       steps:
      - name: Obtener código
        uses: actions/checkout@v5

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Actualizar herramientas
        run: python -m pip install --upgrade pip

      - name: Instalar todo lo necesario
        run: |
          pip install pyinstaller
          pip install ursina

      - name: Crear ejecutable
        run: pyinstaller --onefile --windowed --add-data "*.png;." --add-data "*.obj;." main.py

      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: ViNX0-Juego-Listo
          path: dist/main.exe

"Agrego flujo para crear EXE con Ursina"